### ISSUE TITLE
Adding `eval` support

### ISSUE THREAD

**Issue by guillaumebriday** [stimulus-components/stimulus-remote-rails#3]

**Comment by glaszig** [comment]
quickly took a stab at this. what happens is that rails-ujs already detects if the response if js and does the following:

```js
// const responseText = 'alert("hello world!")'
const script = document.createElement("script")
script.setAttribute("nonce", cspNonce())
script.text = responseText

document.head
  .appendChild(script)
  .parentNode.removeChild(script)

```

stimulus-remote-rails then goes on and inserts what's in `responseText` as html.

what do you intend to do here?

**Comment by guillaumebriday** [comment]
Yep, I already did that here https://github.com/stimulus-components/stimulus-content-loader/blob/master/src/index.ts#L93

I need to back port it in this package 👍

**Comment by guillaumebriday** [comment]
Hum, I need to check how it behaves, maybe there is nothing to do.
