### ISSUE TITLE
Target element

### ISSUE THREAD

**Issue by alextakitani** [stimulus-components/stimulus-remote-rails#4]
I don't know If this controller is suitable for my case, so sorry if it's not the case.

I want on a click of a button, to render a partial or an error message.

But I need it to render to a specific point on my page.

So, is there a way to define the target element? 

Thanks!

**Comment by guillaumebriday** [comment]
Not yet but it's a good suggestion, there isn't much to do to add this feature if you want to open a PR ?

Thanks

**Comment by guillaumebriday** [comment]
Targets must be inside the element though, because we must put `data-remote="true"` on the same element as the controller
