### ISSUE TITLE
Issue with Yarn Install of the plugin

### ISSUE THREAD

**Issue by cwseric** [stimulus-components/stimulus-remote-rails#6]
Hi,

I'm very new to how stimulus and the packaging of these javascript files work however I ran the `yarn install stimulus-remote-rails` and it put some stuff in my node_modules section. When I add `Import Remote from "stimulus-remote-rails"` my editor shows an error:

Could not find a declaration file for module 'stimulus-remote-rails'. '/.../node_modules/stimulus-remote-rails/dist/stimulus-remote-rails.umd.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/stimulus-remote-rails` if it exists or add a new declaration (.d.ts) file containing `declare module 'stimulus-remote-rails';`

I'm not sure how to fix this, but I dont have the /src folder that you have in the git repo.

Thanks

**Comment by guillaumebriday** [comment]
It's because I don't export Typescript declaration file at the moment. Just ignore them for now please 👍
